update based on feedback

diff --git a/.github/workflows/docker-build-and-run.yaml b/.github/workflows/docker-build-and-run.yaml
--- a/.github/workflows/docker-build-and-run.yaml
+++ b/.github/workflows/docker-build-and-run.yaml
@@ -13,6 +13,13 @@ jobs:
       - name: Checkout Repository
         uses: actions/checkout@v2
 
+      - name: Install jq
+        run: |
+          if ! command -v jq &> /dev/null; then
+            sudo apt-get update
+            sudo apt-get install jq
+          fi
+
       - name: Build Docker Image
         run: docker build -t owm-productizer .
 
@@ -24,16 +31,22 @@ jobs:
 
       - name: Test API
         run: |
-          response=$(curl -s -w "%{http_code}" http://localhost:8000/Weather/Current/Metric_v1.0 -d '{"lat":60.192059, "lon":24.945831}')
+          response=$(curl -s -w "%{http_code}" -H 'Content-Type: application/json' http://localhost:8000/Weather/Current/Metric_v1.0 -d '{"lat":60.192059, "lon":24.945831}')
           echo "API Response: $response"
-          if [[ $response -ne 200 ]]; then
+
+          status_code=$(echo "$response" | sed 's/.*\([0-9]\{3\}\)$/\1/')
+          json_resp=$(echo "$response" | sed 's/\([0-9]\{3\}\)$//')
+
+          if [[ $status_code -ne 200 ]]; then
               echo "API test failed. HTTP status code is not 200."
               exit 1
           fi
 
-          # Check if the response structure is as expected
-          if [[ "$response" != *"humidity"* || "$response" != *"pressure"* || "$response" != *"rain"* || "$response" != *"temp"* || "$response" != *"windSpeed"* || "$response" != *"windDirection"* ]]; then
-            echo "API test failed. Response structure is not as expected."
+          # Check if the response is a valid JSON using jq
+          if echo "$json_resp" | jq -e . > /dev/null 2>&1; then
+            echo "API test passed. Response structure is a valid JSON."
+          else
+            echo "API test failed. Response structure is not a valid JSON."
             exit 1
           fi
 
